# Úvod do Pandas

[Pandas](https://pandas.pydata.org/) je rozšírená open-source Python knižnica, ktorá ponúka štruktúrya funkcie na 
analýzu dát. Hlavným cieľom tejto knižnice je poskutnúť pokročilú dátovú analytiku s minimom programovania.

V praxi sa jedná o tabuľku, ktorá sa volá `DataFrame`, ktorá obsahuje naše dáta, nad ktorou vieme vykonávať rôzne 
operácie.

Pre naše potešenie je celá knižnica detailne zdokumentovaná na nasledovnom odkaze:
[Pandas Docs](https://pandas.pydata.org/pandas-docs/stable/). Dokumentácia je vždy náš najlepší kamoš.

Predtým ako začneme pracovať, musíme Python-u povedať, že cheme s Pandas pracovať:

In [9]:
# Import knižníc
import pandas as pd
import numpy as np

# Schovaj nudné upozornenia
import warnings
warnings.filterwarnings('ignore')


Python už vie, že sa chceme hrať s Pandas, teraz si potrebujeme vytvoriť dataframe (`df`) s našimi dátami.

Pandas má na to hneď niekoľko možností (záleží v akej forme sme dáta dostali):

- [pandas.read_csv](http://pandas.pydata.org/pandas-docs/version/0.21/generated/pandas.read_csv.html): CSV súbory
- [pandas.read_excel](http://pandas.pydata.org/pandas-docs/version/0.21/generated/pandas.read_excel.html#pandas.read_excel): Excel
- [pandas.read_json](http://pandas.pydata.org/pandas-docs/version/0.21/generated/pandas.read_json.html#pandas.read_json): JSON


Náš prvý dataset som pripravil vo formáte CSV (Comma separated values), jedná sa o jednoduchý textový súbor, kde sú
hodnoty oddelené čiarkou, prípadne iným jednoznakovým oddelovačom (napríklad `;`, ` `, `|`, `,`).

In [2]:
df = pd.read_csv('../../data/bmi.csv', sep=';')

## Prvotná analýza

Už máme načítané dáta v premennej `df`, teraz ideme postupne objavovať čo všetko nám vedia povedať. Je dobrým zvykom
začať zistením aké dáta máme, ako vyzerajú a koľko ich je. K tomu nám pomôžu nasledujúce atribúty a funkcie:

- [pandas.DataFrame.info()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html): 
Základné informácie o tabuľke
- [pandas.DataFrame.shape](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.shape.html):
Rozmer tabuľky
- [pandas.DataFrame.head()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.head.html):
Prvých 5 záznamov v tabuľke
- [pandas.DataFrame.tail()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.tail.html):
Posledných 5 záznamov v tabuľke

Jedna z výhod Jupyter Notebooks je, že dokážu veľmi efektívne pracovať s pandas DataFrames, napríklad stačí iba zavolať
názov premennej ktorá obsahuje DataFrame (napríklad `df`) a Jupyter rovno vykreslí celú tabuľku.

In [3]:
df.info()
# df.shape
# df.head()
# df.tail()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 4 columns):
Unnamed: 0    32 non-null int64
Name          32 non-null object
Height        32 non-null float64
Weight        32 non-null int64
dtypes: float64(1), int64(2), object(1)
memory usage: 1.1+ KB

    Unnamed: 0             Name  Height  Weight
0            0         Iron Man    1.64     119
1            1             Thor    2.13     139
2            2          Ant-Man    1.76      61
3            3             Wasp    1.74     125
4            4             Hulk    1.80     131
5            5  Captain America    1.61     110
6            6          Hawkeye    1.61     111
7            7      Quicksilver  -12.21     110
8            8    Scarlet Witch    2.14      53
9            9        Swordsman    1.63     123
10          10         Hercules    1.99     113
11          11    Black Panther    2.04     120
12          12           Vision    1.98     119
13          13     Black Knight    1.92      54
14          14      Black Widow    2.12     124
15          15           Mantis    1.96     123
16          16            Beast    2.06      52
17          17       Moondragon    2.09      97
18          18          Hellcat    1.61     131
19          19      Two-Gun Kid    1.81      -7
20          20       Wonder Man    1.70     127
21          21            Thing    1.87      62
22          22      Human Torch    2.05      77
23          23       Spider-Man    2.15     101
24          24          Sandman    1.99     136
25          25          Justice    2.11     136
26          26        Wolverine    2.15      96
27          27   Doctor Strange    1.70      62
28          28        Daredevil    1.87      64
29          29          Gandalf    1.81      79
30          30   Sheldon Cooper    2.11     120
31          31     Chuck Norris    2.12     132

## Príprava dát

Predtým ako začneme reálnu analýzu, musíme sa pozrieť aké máme k dispozícii dáta a či sú v správnej forme. Aby sme
zabezpečili čo najväčšiu presnosť našich zistení a záverov, musíme odstrániť neuplné alebo poškodené dáta, prípadne 
upraviť stĺpce do dobre čitateľnej podoby.

Ako prvú vec, čo si všimnem je, že prvý stĺpec je nejaký divný a nemá pre nás žiadnu špeciálnu hodnotu, dáme ho preč.

Pomôžeme si prístupom cez konštrukciu 
[pandas.DataFrame.iloc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html#pandas.DataFrame.iloc)

In [4]:
df = df.iloc[:, 1:]
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 3 columns):
Name      32 non-null object
Height    32 non-null float64
Weight    32 non-null int64
dtypes: float64(1), int64(1), object(1)
memory usage: 848.0+ bytes

               Name  Height  Weight
0          Iron Man    1.64     119
1              Thor    2.13     139
2           Ant-Man    1.76      61
3              Wasp    1.74     125
4              Hulk    1.80     131
5   Captain America    1.61     110
6           Hawkeye    1.61     111
7       Quicksilver  -12.21     110
8     Scarlet Witch    2.14      53
9         Swordsman    1.63     123
10         Hercules    1.99     113
11    Black Panther    2.04     120
12           Vision    1.98     119
13     Black Knight    1.92      54
14      Black Widow    2.12     124
15           Mantis    1.96     123
16            Beast    2.06      52
17       Moondragon    2.09      97
18          Hellcat    1.61     131
19      Two-Gun Kid    1.81      -7
20       Wonder Man    1.70     127
21            Thing    1.87      62
22      Human Torch    2.05      77
23       Spider-Man    2.15     101
24          Sandman    1.99     136
25          Justice    2.11     136
26        Wolverine    2.15      96
27   Doctor Strange    1.70      62
28        Daredevil    1.87      64
29          Gandalf    1.81      79
30   Sheldon Cooper    2.11     120
31     Chuck Norris    2.12     132

Každá tabuľka potrebuje nejaké referenčné body, musíme mať správne označené stĺpce a niekedy nám príde vhodné aj správne
pomenovať riadky. Napríklad, všetky údaje v riadku sa týkajú jednej osoby, ktorá je identifikovaná svojím menom.

V pandas sa niečo takéto volá index, vytvorme si teda index pre riadok na základe stĺpca `Name`.

Pomôcka: [set_index](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.set_index.html).

In [5]:
df = df.set_index(['Name'])
df.head()
df.info()
df

<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, Iron Man to Chuck Norris
Data columns (total 2 columns):
Height    32 non-null float64
Weight    32 non-null int64
dtypes: float64(1), int64(1)
memory usage: 768.0+ bytes

                 Height  Weight
Name
Iron Man           1.64     119
Thor               2.13     139
Ant-Man            1.76      61
Wasp               1.74     125
Hulk               1.80     131
Captain America    1.61     110
Hawkeye            1.61     111
Quicksilver      -12.21     110
Scarlet Witch      2.14      53
Swordsman          1.63     123
Hercules           1.99     113
Black Panther      2.04     120
Vision             1.98     119
Black Knight       1.92      54
Black Widow        2.12     124
Mantis             1.96     123
Beast              2.06      52
Moondragon         2.09      97
Hellcat            1.61     131
Two-Gun Kid        1.81      -7
Wonder Man         1.70     127
Thing              1.87      62
Human Torch        2.05      77
Spider-Man         2.15     101
Sandman            1.99     136
Justice            2.11     136
Wolverine          2.15      96
Doctor Strange     1.70      62
Daredevil          1.87      64
Gandalf            1.81      79
Sheldon Cooper     2.11     120
Chuck Norris       2.12     132

Je vždy dobré pre kalkuláciou pozrieť sa, či namerané hodnoty dávajú zmysel. Napríklad, ak máme nejaké nulové alebo 
záporné hodnoty, s vysokou pravdepodobnosťou je to chyba merania. Tieto dáta pre nás strácajú zmysel.

Pokúsime sa najprv takéto hodnoty nájsť, teraz to skúsime cez konštrukciu 
[pandas.DataFrame.loc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html)
ktorá pristupuje k dátam tabuľky cez názvy stĺpcov a indexov.

In [10]:
mask = (df['Height'] < 0) | (df['Weight'] < 0)
df.loc[mask]

df['Height'][df['Height'] < 0] = np.NaN
df['Weight'][df['Weight'] < 0] = np.NaN

df

                 Height  Weight        BMI       BMI Category
Name
Iron Man           1.64   119.0  44.244497            Nadváha
Thor               2.13   139.0  30.637660            Nadváha
Ant-Man            1.76    61.0  19.692665            Podváha
Wasp               1.74   125.0  41.286828            Nadváha
Hulk               1.80   131.0  40.432099            Nadváha
Captain America    1.61   110.0  42.436634            Nadváha
Hawkeye            1.61   111.0  42.822422            Nadváha
Scarlet Witch      2.14    53.0  11.573063            Podváha
Swordsman          1.63   123.0  46.294554            Nadváha
Hercules           1.99   113.0  28.534633            Nadváha
Black Panther      2.04   120.0  28.835063            Nadváha
Vision             1.98   119.0  30.354046            Nadváha
Black Knight       1.92    54.0  14.648438            Podváha
Black Widow        2.12   124.0  27.589890            Nadváha
Mantis             1.96   123.0  32.017909            Nadváha
Beast              2.06    52.0  12.253747            Podváha
Moondragon         2.09    97.0  22.206451  Normálna hmotnosť
Hellcat            1.61   131.0  50.538174            Nadváha
Wonder Man         1.70   127.0  43.944637            Nadváha
Thing              1.87    62.0  17.729989            Podváha
Human Torch        2.05    77.0  18.322427            Podváha
Spider-Man         2.15   101.0  21.849648  Normálna hmotnosť
Sandman            1.99   136.0  34.342567            Nadváha
Justice            2.11   136.0  30.547382            Nadváha
Wolverine          2.15    96.0  20.767983  Normálna hmotnosť
Doctor Strange     1.70    62.0  21.453287  Normálna hmotnosť
Daredevil          1.87    64.0  18.301925            Podváha
Gandalf            1.81    79.0  24.114038  Normálna hmotnosť
Sheldon Cooper     2.11   120.0  26.953572            Nadváha
Chuck Norris       2.12   132.0  29.369883            Nadváha

Už naše dáta vyzerajú v poriadku, môžeme začať počítať BMI.

In [ ]:
df['BMI'] = df['Weight'] / (df['Height'] ** 2)
df = df.dropna()
df

Na základe BMI, vieme ľudí zaradiť minimálne do troch kategórií:

- Podváha
- Normálna hmotnosť
- Nadváha

Vytvorme teda stĺpec `BMI Category`, ktorú bude hovoriť o hrdinovy do akej kategórie spadá.

In [12]:
df['BMI Category'] = np.NaN
df['BMI Category'][df['BMI'] < 20] = 'Podváha'
df['BMI Category'][(df['BMI'] >= 20) & (df['BMI'] < 25)] = 'Normálna hmotnosť'
df['BMI Category'][df['BMI'] >= 25] = 'Nadváha'

df

                 Height  Weight        BMI       BMI Category
Name
Iron Man           1.64   119.0  44.244497            Nadváha
Thor               2.13   139.0  30.637660            Nadváha
Ant-Man            1.76    61.0  19.692665            Podváha
Wasp               1.74   125.0  41.286828            Nadváha
Hulk               1.80   131.0  40.432099            Nadváha
Captain America    1.61   110.0  42.436634            Nadváha
Hawkeye            1.61   111.0  42.822422            Nadváha
Scarlet Witch      2.14    53.0  11.573063            Podváha
Swordsman          1.63   123.0  46.294554            Nadváha
Hercules           1.99   113.0  28.534633            Nadváha
Black Panther      2.04   120.0  28.835063            Nadváha
Vision             1.98   119.0  30.354046            Nadváha
Black Knight       1.92    54.0  14.648438            Podváha
Black Widow        2.12   124.0  27.589890            Nadváha
Mantis             1.96   123.0  32.017909            Nadváha
Beast              2.06    52.0  12.253747            Podváha
Moondragon         2.09    97.0  22.206451  Normálna hmotnosť
Hellcat            1.61   131.0  50.538174            Nadváha
Wonder Man         1.70   127.0  43.944637            Nadváha
Thing              1.87    62.0  17.729989            Podváha
Human Torch        2.05    77.0  18.322427            Podváha
Spider-Man         2.15   101.0  21.849648  Normálna hmotnosť
Sandman            1.99   136.0  34.342567            Nadváha
Justice            2.11   136.0  30.547382            Nadváha
Wolverine          2.15    96.0  20.767983  Normálna hmotnosť
Doctor Strange     1.70    62.0  21.453287  Normálna hmotnosť
Daredevil          1.87    64.0  18.301925            Podváha
Gandalf            1.81    79.0  24.114038  Normálna hmotnosť
Sheldon Cooper     2.11   120.0  26.953572            Nadváha
Chuck Norris       2.12   132.0  29.369883            Nadváha

## Analýza

Už máme vypočítané všetky potrebné dáta, môžeme začať klásť otázky a kresliť grafy.

1. Koľko superhrdinov trpí obezitou?
2. Koláčový graf (Pie chart) váhových kategórií 
([pandas.DataFrame.plot.pie](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.plot.pie.html))
3.